export const CONTACT_FIELD_LABELS: Record<string, string> = {
  first_name: "First name",
  last_name: "Last name",
  email: "Email",
  phone: "Phone",
  company_id: "Organization",
  title: "Title",
  address_line_1: "Address line 1",
  address_line_2: "Address line 2",
  city: "City",
  state: "State",
  postal_code: "Postal code",
  country: "Country",
  website: "Website",
  notes: "Notes",
  source: "Source",
};

export const LEAD_FIELD_LABELS: Record<string, string> = {
  title: "Lead title",
  status: "Status",
  source: "Source",
  value_minor: "Value",
  first_name: "First name",
  last_name: "Last name",
  email: "Email",
  phone: "Phone",
  contact_title: "Title",
  company_id: "Organization",
  company_name: "Organization",
  address_line_1: "Address line 1",
  address_line_2: "Address line 2",
  city: "City",
  state: "State",
  postal_code: "Postal code",
  country: "Country",
  website: "Website",
  notes: "Notes",
  person_id: "Person",
};

export const COMPANY_FIELD_LABELS: Record<string, string> = {
  name: "Company",
  website: "Website",
  phone: "Phone",
  email: "Email",
  industry: "Industry",
  city: "City",
  state: "State",
  postal_code: "Postal code",
  country: "Country",
  address_line_1: "Address line 1",
  address_line_2: "Address line 2",
  notes: "Notes",
};
