/**
 * Public SEO template library catalog.
 * Source: SendDox Free Template Library — SEO + Product Acquisition Research.
 * URL architecture: /templates/{category}/{slug}
 */

export type MarketingTemplateCategory = {
  slug: string;
  name: string;
  navLabel: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  /** Maps to in-app Sample Templates folder when present. */
  sampleFolderSlug?: string;
};

export type MarketingTemplate = {
  slug: string;
  categorySlug: string;
  name: string;
  /** Primary search phrase, e.g. "NDA Template". */
  primaryKeyword: string;
  seoTitle: string;
  seoDescription: string;
  summary: string;
  whenToUse: string[];
  whatIsIncluded: string[];
  howToCustomize: string[];
  /** Approx. U.S. monthly searches (directional). */
  searchVolumeLabel: string;
  /** 1–5 product fit from research. */
  appFit: 1 | 2 | 3 | 4 | 5;
  wave1?: boolean;
  relatedSlugs?: string[];
};

export const MARKETING_TEMPLATE_CATEGORIES: readonly MarketingTemplateCategory[] = [
  {
    slug: "agreements",
    name: "Agreements & NDA Templates",
    navLabel: "Agreements & NDAs",
    description:
      "NDAs, MSAs, DPAs, contractor agreements, and other B2B agreements built to send, track, and e-sign.",
    seoTitle: "Free Agreements & NDA Templates | SendDox",
    seoDescription:
      "Free NDA, MSA, DPA, and agreement templates. Customize online, send for review, and collect e-signatures with SendDox.",
    sampleFolderSlug: "legal-agreements-nda",
  },
  {
    slug: "contracts",
    name: "Contract Templates",
    navLabel: "Contracts",
    description:
      "Service, sales, employment, freelance, and industry contracts with collaborative editing and signature-ready fields.",
    seoTitle: "Free Contract Templates | SendDox",
    seoDescription:
      "Browse free contract templates for services, sales, employment, and freelancers. Edit, approve, send, and e-sign in SendDox.",
    sampleFolderSlug: "contracts",
  },
  {
    slug: "proposals",
    name: "Proposal Templates",
    navLabel: "Proposals",
    description:
      "Business, sales, marketing, consulting, and project proposals designed to convert prospects into signed deals.",
    seoTitle: "Free Proposal Templates | SendDox",
    seoDescription:
      "Free business and sales proposal templates with pricing, scopes, and acceptance. Create, send, and close in SendDox.",
    sampleFolderSlug: "proposal-templates",
  },
  {
    slug: "sales",
    name: "Sales, Billing & Commercial Documents",
    navLabel: "Sales & Billing",
    description:
      "Quotes, invoices, statements of work, purchase orders, and commercial forms that connect pricing to acceptance.",
    seoTitle: "Free Sales, Quote & Invoice Templates | SendDox",
    seoDescription:
      "Free invoice, quote, SOW, and purchase order templates. Build commercial documents and send them for acceptance in SendDox.",
    sampleFolderSlug: "billing-commercial",
  },
  {
    slug: "hr",
    name: "HR & Employment Templates",
    navLabel: "HR & Employment",
    description:
      "Offer letters, employment contracts, handbooks, and HR forms for hiring, onboarding, and people operations.",
    seoTitle: "Free HR & Employment Templates | SendDox",
    seoDescription:
      "Free offer letter, employment contract, and HR templates. Customize and collect signatures with SendDox.",
    sampleFolderSlug: "hr-employment",
  },
  {
    slug: "operations",
    name: "Business Operations & Corporate Templates",
    navLabel: "Operations & Corporate",
    description:
      "Business plans, SOPs, RFPs, board resolutions, and operations documents that expand discovery and internal linking.",
    seoTitle: "Free Business Operations Templates | SendDox",
    seoDescription:
      "Free business plan, SOP, RFP, and operations templates. Create professional docs and collaborate in SendDox.",
    sampleFolderSlug: "business-operations",
  },
] as const;

function t(
  partial: Omit<MarketingTemplate, "seoTitle" | "seoDescription"> & {
    seoTitle?: string;
    seoDescription?: string;
  },
): MarketingTemplate {
  const keyword = partial.primaryKeyword;
  return {
    ...partial,
    seoTitle: partial.seoTitle ?? `Free ${keyword} | SendDox`,
    seoDescription:
      partial.seoDescription ??
      `Download and customize a free ${keyword.toLowerCase()}. Edit online, send for review, and collect e-signatures with SendDox.`,
  };
}

export const MARKETING_TEMPLATES: readonly MarketingTemplate[] = [
  // Agreements
  t({
    slug: "nda-template",
    categorySlug: "agreements",
    name: "NDA Template",
    primaryKeyword: "NDA Template",
    searchVolumeLabel: "~12.4K–12.8K / mo",
    appFit: 5,
    wave1: true,
    summary:
      "A clear mutual or one-way non-disclosure agreement for sharing confidential information with partners, contractors, candidates, and vendors.",
    whenToUse: [
      "Before sharing product roadmaps, pricing, customer lists, or source code",
      "During vendor evaluations, fundraising, or partnership discussions",
      "When onboarding contractors, freelancers, or interview candidates",
    ],
    whatIsIncluded: [
      "Definition of confidential information",
      "Permitted use and non-disclosure obligations",
      "Term, return/destruction, and remedies",
      "Signature blocks for both parties",
    ],
    howToCustomize: [
      "Choose mutual vs one-way language",
      "Add your company details with SendDox variables",
      "Insert signer fields and send for e-signature",
    ],
    relatedSlugs: ["independent-contractor-agreement", "data-processing-agreement", "master-services-agreement"],
  }),
  t({
    slug: "operating-agreement-template",
    categorySlug: "agreements",
    name: "Operating Agreement Template",
    primaryKeyword: "Operating Agreement Template",
    searchVolumeLabel: "Est. 10K–30K / mo",
    appFit: 4,
    summary: "LLC operating agreement covering ownership, voting, distributions, and management.",
    whenToUse: ["Forming an LLC", "Adding members", "Clarifying profit distributions"],
    whatIsIncluded: ["Membership interests", "Management structure", "Transfer restrictions", "Dissolution terms"],
    howToCustomize: ["Add member names and ownership %", "Set manager-managed vs member-managed", "Send for countersignature"],
  }),
  t({
    slug: "data-processing-agreement",
    categorySlug: "agreements",
    name: "Data Processing Agreement Template",
    primaryKeyword: "Data Processing Agreement Template",
    searchVolumeLabel: "~4.8K–6.9K / mo",
    appFit: 5,
    wave1: true,
    summary: "DPA for SaaS and technology vendors processing personal data on behalf of customers.",
    whenToUse: ["Enterprise SaaS sales", "GDPR/CCPA vendor reviews", "Security questionnaires"],
    whatIsIncluded: ["Roles of controller/processor", "Security measures", "Subprocessors", "Data subject rights"],
    howToCustomize: ["Attach your security exhibit", "List subprocessors", "Route Legal for approval before send"],
  }),
  t({
    slug: "software-license-agreement",
    categorySlug: "agreements",
    name: "Software License Agreement",
    primaryKeyword: "Software License Agreement",
    searchVolumeLabel: "~5.3K / mo",
    appFit: 5,
    wave1: true,
    summary: "License terms for software products, including permitted use, restrictions, and support.",
    whenToUse: ["SaaS and on-prem software sales", "Partner embedding deals"],
    whatIsIncluded: ["Grant of license", "Restrictions", "IP ownership", "Warranty and liability"],
    howToCustomize: ["Set license type and seat counts", "Add pricing schedule", "Collect customer signature"],
  }),
  t({
    slug: "independent-contractor-agreement",
    categorySlug: "agreements",
    name: "Independent Contractor Agreement",
    primaryKeyword: "Independent Contractor Agreement",
    searchVolumeLabel: "~3.9K–5.4K / mo",
    appFit: 5,
    wave1: true,
    summary: "Contractor agreement covering scope, payment, IP assignment, and confidentiality.",
    whenToUse: ["Hiring freelancers", "Agency subcontractors", "Project-based consulting"],
    whatIsIncluded: ["Scope of services", "Fees and expenses", "IP assignment", "Termination"],
    howToCustomize: ["Paste SOW as an exhibit", "Add payment milestones", "Send for dual signature"],
  }),
  t({
    slug: "partnership-agreement",
    categorySlug: "agreements",
    name: "Partnership Agreement",
    primaryKeyword: "Partnership Agreement",
    searchVolumeLabel: "~4.2K / mo",
    appFit: 4,
    wave1: true,
    summary: "Defines roles, contributions, profit share, and decision-making for business partners.",
    whenToUse: ["Launching a partnership", "Formalizing co-founder economics"],
    whatIsIncluded: ["Capital contributions", "Profit/loss allocation", "Decision rights", "Exit terms"],
    howToCustomize: ["Set ownership split", "Add non-compete if needed", "Collect partner signatures"],
  }),
  t({
    slug: "professional-services-agreement",
    categorySlug: "agreements",
    name: "Professional Services Agreement",
    primaryKeyword: "Professional Services Agreement",
    searchVolumeLabel: "~3.5K / mo",
    appFit: 5,
    wave1: true,
    summary: "Master professional services terms for consultants, agencies, and IT services firms.",
    whenToUse: ["Recurring client engagements", "Before issuing SOWs"],
    whatIsIncluded: ["Services framework", "Fees", "Confidentiality", "Limitation of liability"],
    howToCustomize: ["Attach rate card", "Link future SOWs", "Send for countersign"],
  }),
  t({
    slug: "master-services-agreement",
    categorySlug: "agreements",
    name: "Master Services Agreement (MSA)",
    primaryKeyword: "Master Services Agreement Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    wave1: true,
    summary: "Enterprise-ready MSA that governs multiple statements of work over time.",
    whenToUse: ["B2B SaaS and consulting relationships", "Multi-project clients"],
    whatIsIncluded: ["Ordering process", "Payment terms", "IP", "Indemnity", "Term"],
    howToCustomize: ["Negotiate liability caps", "Add DPA exhibit", "Approve internally then send"],
  }),
  t({
    slug: "vendor-agreement-template",
    categorySlug: "agreements",
    name: "Vendor Agreement Template",
    primaryKeyword: "Vendor Agreement Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Vendor/supplier agreement for procurement and operations teams.",
    whenToUse: ["Onboarding suppliers", "Annual vendor renewals"],
    whatIsIncluded: ["Supply terms", "SLAs", "Compliance", "Termination"],
    howToCustomize: ["Add SKUs or services", "Set renewal terms", "Collect vendor signature"],
  }),
  t({
    slug: "referral-agreement-template",
    categorySlug: "agreements",
    name: "Referral Agreement Template",
    primaryKeyword: "Referral Agreement Template",
    searchVolumeLabel: "Est. 500–1.5K / mo",
    appFit: 4,
    summary: "Referral partner terms including commission, exclusivity, and attribution.",
    whenToUse: ["Launching a partner program", "Agency referral deals"],
    whatIsIncluded: ["Referral fees", "Qualified lead definition", "Payment timing", "Term"],
    howToCustomize: ["Set commission %", "Define attribution window", "Send for partner signature"],
  }),

  // Contracts
  t({
    slug: "contract-template",
    categorySlug: "contracts",
    name: "Contract Template",
    primaryKeyword: "Contract Template",
    searchVolumeLabel: "550K–1.83M keyword family",
    appFit: 5,
    wave1: true,
    summary: "A versatile business contract foundation for services, deliverables, payment, and signatures.",
    whenToUse: ["General B2B engagements", "When you need a clean starting contract"],
    whatIsIncluded: ["Parties", "Scope", "Payment", "Term", "Signatures"],
    howToCustomize: ["Replace placeholders", "Add exhibits", "Route for approval and e-sign"],
  }),
  t({
    slug: "employment-contract",
    categorySlug: "contracts",
    name: "Employment Contract",
    primaryKeyword: "Employment Contract",
    searchVolumeLabel: "~49.5K / mo",
    appFit: 5,
    wave1: true,
    summary: "Employment agreement covering role, compensation, confidentiality, and at-will or fixed terms.",
    whenToUse: ["Hiring full-time employees", "Updating offer packages"],
    whatIsIncluded: ["Position and duties", "Compensation", "IP/confidentiality", "Termination"],
    howToCustomize: ["Add comp details", "Attach handbook acknowledgment", "Collect employee signature"],
  }),
  t({
    slug: "freelance-contract-template",
    categorySlug: "contracts",
    name: "Freelance Contract Template",
    primaryKeyword: "Freelance Contract Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 5,
    summary: "Freelance services contract with deliverables, revisions, and payment schedule.",
    whenToUse: ["Creator and freelance engagements"],
    whatIsIncluded: ["Deliverables", "Timeline", "Fees", "IP ownership"],
    howToCustomize: ["List milestones", "Set revision rounds", "Send for signature"],
  }),
  t({
    slug: "construction-contract-template",
    categorySlug: "contracts",
    name: "Construction Contract Template",
    primaryKeyword: "Construction Contract Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 4,
    summary: "Construction services contract covering scope, change orders, and payment draws.",
    whenToUse: ["Residential or commercial builds", "Remodel projects"],
    whatIsIncluded: ["Scope of work", "Payment schedule", "Change orders", "Warranties"],
    howToCustomize: ["Attach plans/specs", "Set deposit", "Collect owner signature"],
  }),
  t({
    slug: "service-contract",
    categorySlug: "contracts",
    name: "Service Contract",
    primaryKeyword: "Service Contract",
    searchVolumeLabel: "~1.9K U.S. / ~5.4K global",
    appFit: 5,
    wave1: true,
    summary: "Service contract for recurring or one-time professional services.",
    whenToUse: ["Service businesses", "Maintenance and retainers"],
    whatIsIncluded: ["Services", "Fees", "Client obligations", "Term"],
    howToCustomize: ["Define service levels", "Add billing cadence", "Send for acceptance"],
  }),
  t({
    slug: "consulting-contract-template",
    categorySlug: "contracts",
    name: "Consulting Contract Template",
    primaryKeyword: "Consulting Contract Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Consulting engagement contract with advisory scope and fee structure.",
    whenToUse: ["Advisory projects", "Strategy engagements"],
    whatIsIncluded: ["Objectives", "Fees", "Confidentiality", "Independent contractor status"],
    howToCustomize: ["Add discovery findings", "Set retainer", "Collect signatures"],
  }),
  t({
    slug: "sales-contract-template",
    categorySlug: "contracts",
    name: "Sales Contract Template",
    primaryKeyword: "Sales Contract Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Sale of goods / commercial sales contract with delivery and risk terms.",
    whenToUse: ["Product sales", "Distribution deals"],
    whatIsIncluded: ["Goods description", "Price", "Delivery", "Title and risk"],
    howToCustomize: ["Add SKUs", "Set Incoterms if needed", "Send for buyer signature"],
  }),
  t({
    slug: "software-development-contract",
    categorySlug: "contracts",
    name: "Software Development Contract",
    primaryKeyword: "Software Development Contract",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Development agreement covering milestones, acceptance, and IP ownership.",
    whenToUse: ["Custom software builds", "Agency development projects"],
    whatIsIncluded: ["Milestones", "Acceptance criteria", "IP", "Change requests"],
    howToCustomize: ["Attach backlog/SOW", "Set payment per milestone", "Collect signatures"],
  }),
  t({
    slug: "maintenance-contract-template",
    categorySlug: "contracts",
    name: "Maintenance Contract Template",
    primaryKeyword: "Maintenance Contract Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Recurring maintenance/service agreement with response times and coverage.",
    whenToUse: ["IT, facilities, HVAC, and managed services"],
    whatIsIncluded: ["Covered assets", "SLA", "Fees", "Exclusions"],
    howToCustomize: ["List assets", "Set response windows", "Send for renewal signature"],
  }),
  t({
    slug: "retainer-agreement",
    categorySlug: "contracts",
    name: "Retainer Agreement",
    primaryKeyword: "Retainer Contract / Agreement",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Monthly retainer agreement for marketing, legal, accounting, and consulting retainers.",
    whenToUse: ["Ongoing advisory or agency work"],
    whatIsIncluded: ["Retainer fee", "Included hours", "Overage rates", "Term"],
    howToCustomize: ["Set monthly fee", "Define unused-hour policy", "Collect signature"],
  }),

  // Proposals
  t({
    slug: "business-proposal-template",
    categorySlug: "proposals",
    name: "Business Proposal Template",
    primaryKeyword: "Business Proposal Template",
    searchVolumeLabel: "~5.4K / mo",
    appFit: 5,
    wave1: true,
    summary: "A conversion-focused business proposal with problem, solution, pricing, and next steps.",
    whenToUse: ["New business pitches", "Partnership offers"],
    whatIsIncluded: ["Executive summary", "Approach", "Timeline", "Investment", "Acceptance"],
    howToCustomize: ["Add prospect name variables", "Insert quote table", "Enable tracking and send"],
  }),
  t({
    slug: "project-proposal-template",
    categorySlug: "proposals",
    name: "Project Proposal Template",
    primaryKeyword: "Project Proposal Template",
    searchVolumeLabel: "~4.4K / mo",
    appFit: 5,
    wave1: true,
    summary: "Project proposal covering objectives, scope, milestones, and fees.",
    whenToUse: ["Fixed-scope projects", "Implementation bids"],
    whatIsIncluded: ["Objectives", "Scope", "Milestones", "Budget"],
    howToCustomize: ["Map milestones to dates", "Add pricing block", "Send for acceptance"],
  }),
  t({
    slug: "marketing-proposal-template",
    categorySlug: "proposals",
    name: "Marketing Proposal Template",
    primaryKeyword: "Marketing Proposal Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 5,
    wave1: true,
    summary: "Agency marketing proposal with channels, KPIs, and retainer/project pricing.",
    whenToUse: ["Agency new business", "Campaign pitches"],
    whatIsIncluded: ["Strategy", "Channel plan", "KPIs", "Investment"],
    howToCustomize: ["Swap case studies", "Set package pricing", "Track opens and follow up"],
  }),
  t({
    slug: "seo-proposal-template",
    categorySlug: "proposals",
    name: "SEO Proposal Template",
    primaryKeyword: "SEO Proposal Template",
    searchVolumeLabel: "~1.3K / mo",
    appFit: 5,
    wave1: true,
    summary: "SEO services proposal with audit findings, roadmap, and monthly investment.",
    whenToUse: ["SEO retainers", "Technical SEO projects"],
    whatIsIncluded: ["Findings", "Roadmap", "Deliverables", "Pricing"],
    howToCustomize: ["Paste audit highlights", "Add keyword targets", "Send tracked proposal"],
  }),
  t({
    slug: "sales-proposal-template",
    categorySlug: "proposals",
    name: "Sales Proposal Template",
    primaryKeyword: "Sales Proposal Template",
    searchVolumeLabel: "~1.3K / mo",
    appFit: 5,
    wave1: true,
    summary: "B2B sales proposal aligned to discovery notes, solution fit, and commercial terms.",
    whenToUse: ["Complex B2B deals", "Multi-stakeholder sales"],
    whatIsIncluded: ["Business case", "Solution", "ROI", "Pricing", "Next steps"],
    howToCustomize: ["Pull CRM contact variables", "Attach quote", "Notify team on view activity"],
  }),
  t({
    slug: "consulting-proposal-template",
    categorySlug: "proposals",
    name: "Consulting Proposal Template",
    primaryKeyword: "Consulting Proposal Template",
    searchVolumeLabel: "~1.3K / mo",
    appFit: 5,
    wave1: true,
    summary: "Consulting proposal with diagnosis, workplan, team, and fees.",
    whenToUse: ["Advisory engagements", "Transformation projects"],
    whatIsIncluded: ["Situation assessment", "Workplan", "Team", "Fees"],
    howToCustomize: ["Import discovery notes", "Set phases", "Request e-signature on acceptance"],
  }),
  t({
    slug: "web-design-proposal-template",
    categorySlug: "proposals",
    name: "Web Design Proposal Template",
    primaryKeyword: "Web Design Proposal Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Web design / rebuild proposal with sitemap phases and design deliverables.",
    whenToUse: ["Agency website projects"],
    whatIsIncluded: ["Discovery", "Design", "Build", "Launch", "Investment"],
    howToCustomize: ["Attach moodboards", "Set milestone payments", "Send for approval"],
  }),
  t({
    slug: "construction-proposal-template",
    categorySlug: "proposals",
    name: "Construction Proposal Template",
    primaryKeyword: "Construction Proposal Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Construction bid proposal with line items, allowances, and exclusions.",
    whenToUse: ["Contractor bids", "Remodel estimates"],
    whatIsIncluded: ["Scope", "Line items", "Schedule", "Exclusions"],
    howToCustomize: ["Import estimate", "Add photos", "Collect owner acceptance"],
  }),
  t({
    slug: "software-development-proposal",
    categorySlug: "proposals",
    name: "Software Development Proposal",
    primaryKeyword: "Software Development Proposal",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Software build proposal with phases, assumptions, and commercial options.",
    whenToUse: ["Custom app builds", "MVP projects"],
    whatIsIncluded: ["Approach", "Phases", "Assumptions", "Pricing options"],
    howToCustomize: ["Add architecture sketch", "Offer T&M vs fixed", "Track engagement"],
  }),
  t({
    slug: "sponsorship-proposal-template",
    categorySlug: "proposals",
    name: "Sponsorship Proposal Template",
    primaryKeyword: "Sponsorship Proposal Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 3,
    summary: "Sponsorship deck-style proposal with packages, benefits, and investment tiers.",
    whenToUse: ["Events", "Nonprofit partnerships", "Creator sponsorships"],
    whatIsIncluded: ["Audience", "Packages", "Benefits", "Investment"],
    howToCustomize: ["Add audience metrics", "Set package tiers", "Send for sponsor acceptance"],
  }),

  // Sales & billing
  t({
    slug: "invoice-template",
    categorySlug: "sales",
    name: "Invoice Template",
    primaryKeyword: "Invoice Template",
    searchVolumeLabel: "~165K U.S. / 368K global",
    appFit: 4,
    wave1: true,
    summary: "Professional invoice with line items, taxes, and payment instructions.",
    whenToUse: ["Billing clients", "Milestone invoicing"],
    whatIsIncluded: ["Bill-to", "Line items", "Tax", "Due date", "Payment details"],
    howToCustomize: ["Connect pricing table", "Add Stripe payment after acceptance", "Send and track"],
  }),
  t({
    slug: "purchase-order-template",
    categorySlug: "sales",
    name: "Purchase Order Template",
    primaryKeyword: "Purchase Order Template",
    searchVolumeLabel: "Est. 10K–30K / mo",
    appFit: 5,
    wave1: true,
    summary: "Purchase order for procuring goods or services with approvals.",
    whenToUse: ["Procurement workflows", "Vendor ordering"],
    whatIsIncluded: ["Vendor", "Ship-to", "Line items", "Terms"],
    howToCustomize: ["Add approval routing", "Attach specs", "Send to vendor"],
  }),
  t({
    slug: "estimate-template",
    categorySlug: "sales",
    name: "Estimate Template",
    primaryKeyword: "Estimate Template",
    searchVolumeLabel: "Est. 10K–30K / mo",
    appFit: 4,
    summary: "Project estimate with optional/required line items and validity window.",
    whenToUse: ["Contractors and agencies quoting work"],
    whatIsIncluded: ["Scope summary", "Line items", "Assumptions", "Validity"],
    howToCustomize: ["Toggle optional items", "Convert accepted estimate to agreement"],
  }),
  t({
    slug: "scope-of-work-template",
    categorySlug: "sales",
    name: "Scope of Work Template",
    primaryKeyword: "Scope of Work Template",
    searchVolumeLabel: "Est. 5K–10K / mo",
    appFit: 5,
    wave1: true,
    summary: "SOW-style scope document defining deliverables, timeline, and acceptance.",
    whenToUse: ["Project kickoffs", "Agency engagements"],
    whatIsIncluded: ["Objectives", "Deliverables", "Timeline", "Out of scope"],
    howToCustomize: ["Link to MSA", "Add acceptance criteria", "Collect signature"],
  }),
  t({
    slug: "order-form-template",
    categorySlug: "sales",
    name: "Order Form Template",
    primaryKeyword: "Order Form Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 5,
    summary: "Order form for products or subscription plans with commercial terms.",
    whenToUse: ["SaaS ordering", "Distribution sales"],
    whatIsIncluded: ["Products", "Quantities", "Fees", "Term"],
    howToCustomize: ["Bind to price book", "Add e-sign", "Trigger fulfillment"],
  }),
  t({
    slug: "price-list-template",
    categorySlug: "sales",
    name: "Price List Template",
    primaryKeyword: "Price List Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 3,
    summary: "Shareable price list for products or services.",
    whenToUse: ["Wholesale catalogs", "Service menus"],
    whatIsIncluded: ["SKU/service list", "Unit pricing", "Notes"],
    howToCustomize: ["Import catalog", "Version seasonally", "Share tracked link"],
  }),
  t({
    slug: "credit-application-form",
    categorySlug: "sales",
    name: "Credit Application Form",
    primaryKeyword: "Credit Application Form",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 4,
    summary: "B2B credit application gathering company, banking, and trade references.",
    whenToUse: ["Net-term customer onboarding"],
    whatIsIncluded: ["Company info", "References", "Authorization", "Signature"],
    howToCustomize: ["Add required fields", "Route finance approval", "Store signed PDF"],
  }),
  t({
    slug: "quote-template",
    categorySlug: "sales",
    name: "Quote Template",
    primaryKeyword: "Quote Template",
    searchVolumeLabel: "~2.9K / mo",
    appFit: 5,
    wave1: true,
    summary: "Sales quote with pricing, options, and expiration—ready to accept online.",
    whenToUse: ["SMB quoting", "Service providers"],
    whatIsIncluded: ["Line items", "Discounts", "Validity", "Acceptance"],
    howToCustomize: ["Use quote builder", "Require approval under discount threshold", "Send tracked"],
  }),
  t({
    slug: "statement-of-work-template",
    categorySlug: "sales",
    name: "Statement of Work Template",
    primaryKeyword: "Statement of Work Template",
    searchVolumeLabel: "~2.4K / mo",
    appFit: 5,
    wave1: true,
    summary: "Detailed SOW for IT, consulting, and agency delivery under an MSA.",
    whenToUse: ["Enterprise projects", "Phase-based delivery"],
    whatIsIncluded: ["Deliverables", "Roles", "Timeline", "Fees", "Acceptance"],
    howToCustomize: ["Reference MSA", "Add RACI", "Collect dual signature"],
  }),
  t({
    slug: "sales-order-template",
    categorySlug: "sales",
    name: "Sales Order Template",
    primaryKeyword: "Sales Order Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Sales order confirming purchased goods, ship dates, and totals.",
    whenToUse: ["Wholesale and manufacturing order confirmation"],
    whatIsIncluded: ["Order lines", "Ship-to", "Totals", "Terms"],
    howToCustomize: ["Pull CRM account", "Confirm inventory notes", "Send acknowledgment"],
  }),

  // HR
  t({
    slug: "job-description-template",
    categorySlug: "hr",
    name: "Job Description Template",
    primaryKeyword: "Job Description Template",
    searchVolumeLabel: "Est. 20K–50K / mo",
    appFit: 3,
    summary: "Structured job description with responsibilities, requirements, and leveling.",
    whenToUse: ["Opening a role", "Recruiting briefs"],
    whatIsIncluded: ["Summary", "Responsibilities", "Requirements", "Benefits"],
    howToCustomize: ["Align to leveling framework", "Publish internally"],
  }),
  t({
    slug: "performance-review-template",
    categorySlug: "hr",
    name: "Performance Review Template",
    primaryKeyword: "Performance Review Template",
    searchVolumeLabel: "Est. 10K–30K / mo",
    appFit: 4,
    summary: "Performance review form for goals, competencies, and manager feedback.",
    whenToUse: ["Annual or quarterly reviews"],
    whatIsIncluded: ["Goals", "Ratings", "Comments", "Signatures"],
    howToCustomize: ["Add competency model", "Collect employee + manager signatures"],
  }),
  t({
    slug: "offer-letter-template",
    categorySlug: "hr",
    name: "Offer Letter Template",
    primaryKeyword: "Offer Letter Template",
    searchVolumeLabel: "Est. 6K–15K / mo",
    appFit: 5,
    wave1: true,
    summary: "Employment offer letter with compensation, start date, and contingency language.",
    whenToUse: ["Extending offers", "Executive packages"],
    whatIsIncluded: ["Role", "Comp", "Benefits summary", "Acceptance"],
    howToCustomize: ["Fill candidate variables", "Attach equity exhibit", "Collect e-signature"],
  }),
  t({
    slug: "employee-handbook-template",
    categorySlug: "hr",
    name: "Employee Handbook Template",
    primaryKeyword: "Employee Handbook Template",
    searchVolumeLabel: "~4.4K / mo",
    appFit: 4,
    wave1: true,
    summary: "Starter employee handbook outline with acknowledgment signature page.",
    whenToUse: ["SMB policy launch", "Annual handbook refresh"],
    whatIsIncluded: ["Conduct", "Time off", "Benefits overview", "Acknowledgment"],
    howToCustomize: ["Insert local policies", "Require acknowledgment signature"],
  }),
  t({
    slug: "employee-evaluation-form",
    categorySlug: "hr",
    name: "Employee Evaluation Form",
    primaryKeyword: "Employee Evaluation Form",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 4,
    summary: "Evaluation form for structured feedback and scoring.",
    whenToUse: ["Probation reviews", "Promotion packets"],
    whatIsIncluded: ["Criteria", "Scores", "Comments", "Signatures"],
    howToCustomize: ["Weight criteria", "Route HR approval"],
  }),
  t({
    slug: "employee-write-up-form",
    categorySlug: "hr",
    name: "Employee Write-Up Form",
    primaryKeyword: "Employee Write-Up Form",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 4,
    summary: "Disciplinary write-up documenting incident, expectations, and acknowledgment.",
    whenToUse: ["Performance coaching", "Policy violations"],
    whatIsIncluded: ["Incident", "Prior notice", "Expectations", "Signatures"],
    howToCustomize: ["Attach evidence", "Collect employee acknowledgment"],
  }),
  t({
    slug: "termination-letter-template",
    categorySlug: "hr",
    name: "Termination Letter Template",
    primaryKeyword: "Termination Letter Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 5,
    summary: "Employment termination letter with final pay and return-of-property notes.",
    whenToUse: ["Involuntary separations"],
    whatIsIncluded: ["Effective date", "Final pay", "Benefits info", "Return of property"],
    howToCustomize: ["Counsel with legal", "Deliver with acknowledgment"],
  }),
  t({
    slug: "employee-onboarding-checklist",
    categorySlug: "hr",
    name: "Employee Onboarding Checklist",
    primaryKeyword: "Employee Onboarding Checklist",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 3,
    summary: "Onboarding checklist covering IT, HR paperwork, and first-week ramp.",
    whenToUse: ["New hire week-one"],
    whatIsIncluded: ["Pre-board", "Day 1", "Week 1", "Owners"],
    howToCustomize: ["Assign owners", "Attach required forms"],
  }),
  t({
    slug: "remote-work-policy-template",
    categorySlug: "hr",
    name: "Remote Work Policy Template",
    primaryKeyword: "Remote Work Policy Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 4,
    summary: "Remote/hybrid work policy covering eligibility, equipment, and security.",
    whenToUse: ["Distributed teams", "Hybrid transitions"],
    whatIsIncluded: ["Eligibility", "Equipment", "Security", "Acknowledgment"],
    howToCustomize: ["Set location rules", "Require acknowledgment signature"],
  }),
  t({
    slug: "commission-agreement-template",
    categorySlug: "hr",
    name: "Commission Agreement Template",
    primaryKeyword: "Commission Agreement Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Sales commission plan agreement with quotas, rates, and clawbacks.",
    whenToUse: ["AE/AM compensation plans"],
    whatIsIncluded: ["Quota", "Rates", "Payment timing", "Clawbacks"],
    howToCustomize: ["Attach plan exhibit", "Collect seller signature"],
  }),

  // Operations
  t({
    slug: "business-plan-template",
    categorySlug: "operations",
    name: "Business Plan Template",
    primaryKeyword: "Business Plan Template",
    searchVolumeLabel: "Up to ~673K / mo",
    appFit: 3,
    wave1: true,
    summary: "Business plan outline for founders covering market, model, and financials.",
    whenToUse: ["Fundraising", "Internal strategy"],
    whatIsIncluded: ["Opportunity", "Go-to-market", "Ops", "Financials"],
    howToCustomize: ["Add traction metrics", "Share with advisors"],
  }),
  t({
    slug: "meeting-agenda-template",
    categorySlug: "operations",
    name: "Meeting Agenda Template",
    primaryKeyword: "Meeting Agenda Template",
    searchVolumeLabel: "~40.5K / mo",
    appFit: 2,
    summary: "Meeting agenda with topics, owners, and timeboxes.",
    whenToUse: ["Recurring team meetings"],
    whatIsIncluded: ["Topics", "Owners", "Timeboxes", "Notes"],
    howToCustomize: ["Pre-fill attendees", "Share before meeting"],
  }),
  t({
    slug: "sop-template",
    categorySlug: "operations",
    name: "SOP Template",
    primaryKeyword: "SOP Template",
    searchVolumeLabel: "Est. 20K–50K / mo",
    appFit: 3,
    summary: "Standard operating procedure template with steps, owners, and revision history.",
    whenToUse: ["Documenting repeatable processes"],
    whatIsIncluded: ["Purpose", "Steps", "Owners", "Revision log"],
    howToCustomize: ["Add screenshots", "Version and publish"],
  }),
  t({
    slug: "meeting-minutes-template",
    categorySlug: "operations",
    name: "Meeting Minutes Template",
    primaryKeyword: "Meeting Minutes Template",
    searchVolumeLabel: "Est. 10K–30K / mo",
    appFit: 3,
    summary: "Meeting minutes capturing decisions, actions, and owners.",
    whenToUse: ["Board and leadership meetings"],
    whatIsIncluded: ["Attendees", "Decisions", "Actions", "Next meeting"],
    howToCustomize: ["Assign actions", "Circulate for acknowledgment"],
  }),
  t({
    slug: "board-resolution-template",
    categorySlug: "operations",
    name: "Board Resolution Template",
    primaryKeyword: "Board Resolution Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 4,
    summary: "Corporate board resolution for authorizing key company actions.",
    whenToUse: ["Financing", "Officer appointments", "Major contracts"],
    whatIsIncluded: ["Recitals", "Resolutions", "Certification", "Signatures"],
    howToCustomize: ["Insert action language", "Collect director signatures"],
  }),
  t({
    slug: "rfp-template",
    categorySlug: "operations",
    name: "RFP Template",
    primaryKeyword: "RFP Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 5,
    wave1: true,
    summary: "Request for proposal outlining requirements, evaluation, and submission instructions.",
    whenToUse: ["Vendor selection", "Enterprise procurement"],
    whatIsIncluded: ["Background", "Requirements", "Evaluation", "Timeline"],
    howToCustomize: ["Add scoring rubric", "Distribute to vendors", "Track responses"],
  }),
  t({
    slug: "expense-report-template",
    categorySlug: "operations",
    name: "Expense Report Template",
    primaryKeyword: "Expense Report Template",
    searchVolumeLabel: "Est. 3K–10K / mo",
    appFit: 3,
    summary: "Employee expense report with line items and manager approval.",
    whenToUse: ["Travel and expense reimbursement"],
    whatIsIncluded: ["Lines", "Totals", "Receipts note", "Approvals"],
    howToCustomize: ["Set categories", "Route manager approval"],
  }),
  t({
    slug: "project-charter-template",
    categorySlug: "operations",
    name: "Project Charter Template",
    primaryKeyword: "Project Charter Template",
    searchVolumeLabel: "~4.4K / mo",
    appFit: 3,
    summary: "Project charter defining goals, stakeholders, and success metrics.",
    whenToUse: ["Project kickoff", "PMO governance"],
    whatIsIncluded: ["Objectives", "Scope", "Stakeholders", "Success metrics"],
    howToCustomize: ["Add sponsor", "Collect kickoff approval"],
  }),
  t({
    slug: "rfq-template",
    categorySlug: "operations",
    name: "RFQ Template",
    primaryKeyword: "RFQ Template",
    searchVolumeLabel: "Est. 1K–3K / mo",
    appFit: 5,
    summary: "Request for quote focused on priced bids for specified goods/services.",
    whenToUse: ["Procurement price discovery"],
    whatIsIncluded: ["Specs", "Quantities", "Due date", "Terms"],
    howToCustomize: ["List SKUs", "Send to suppliers", "Compare responses"],
  }),
  t({
    slug: "vendor-onboarding-form",
    categorySlug: "operations",
    name: "Vendor Onboarding Form",
    primaryKeyword: "Vendor Onboarding Form",
    searchVolumeLabel: "Est. 500–1.5K / mo",
    appFit: 5,
    summary: "Vendor onboarding packet collecting tax, banking, and compliance details.",
    whenToUse: ["New supplier setup"],
    whatIsIncluded: ["Company info", "Tax forms", "Banking", "Contacts", "Signature"],
    howToCustomize: ["Require W-9 upload field", "Route finance review", "Store signed packet"],
  }),
];

export function marketingCategoryBySlug(slug: string): MarketingTemplateCategory | undefined {
  return MARKETING_TEMPLATE_CATEGORIES.find((category) => category.slug === slug);
}

export function marketingTemplatesByCategory(categorySlug: string): MarketingTemplate[] {
  return MARKETING_TEMPLATES.filter((template) => template.categorySlug === categorySlug);
}

export function marketingTemplateByPath(
  categorySlug: string,
  templateSlug: string,
): MarketingTemplate | undefined {
  return MARKETING_TEMPLATES.find(
    (template) => template.categorySlug === categorySlug && template.slug === templateSlug,
  );
}

export function marketingTemplateHref(template: Pick<MarketingTemplate, "categorySlug" | "slug">): string {
  return `/templates/${template.categorySlug}/${template.slug}`;
}

export function wave1Templates(): MarketingTemplate[] {
  return MARKETING_TEMPLATES.filter((template) => template.wave1);
}
